from rai.config import (
    BRAVE_SEARCH_API_KEY,
    CHUNK_OVERLAP,
    CHUNK_SIZE,
    CONTENT_EXTRACTION_ENGINE,
    DOCS_DIR,
    ENABLE_RAG_HYBRID_SEARCH,
    ENABLE_RAG_WEB_LOADER_SSL_VERIFICATION,
    ENABLE_RAG_WEB_SEARCH,
    GOOGLE_PSE_API_KEY,
    GOOGLE_PSE_ENGINE_ID,
    PDF_EXTRACT_IMAGES,
    RAG_EMBEDDING_ENGINE,
    RAG_EMBEDDING_MODEL,
    OLLAMA_PORT,
    OLLAMA_HOST,
    OPENAI_API_KEY,
DEFAULT_OLLAMA_EMBEDDING_MODEL,
    RAG_EMBEDDING_MODEL_AUTO_UPDATE,
    RAG_EMBEDDING_MODEL_TRUST_REMOTE_CODE,
    RAG_EMBEDDING_OPENAI_BATCH_SIZE,
    RAG_FILE_MAX_COUNT,
    RAG_FILE_MAX_SIZE,
    RAG_OPENAI_API_BASE_URL,
    RAG_OPENAI_API_KEY,
    RAG_RELEVANCE_THRESHOLD,
    RAG_RERANKING_MODEL,
    RAG_RERANKING_MODEL_AUTO_UPDATE,
    RAG_RERANKING_MODEL_TRUST_REMOTE_CODE,
    DEFAULT_RAG_TEMPLATE,
    RAG_TEMPLATE,
    RAG_TOP_K,
    RAG_WEB_SEARCH_CONCURRENT_REQUESTS,
    RAG_WEB_SEARCH_DOMAIN_FILTER_LIST,
    RAG_WEB_SEARCH_ENGINE,
    RAG_WEB_SEARCH_RESULT_COUNT,
    SEARCHAPI_API_KEY,
    SEARCHAPI_ENGINE,
    SEARXNG_QUERY_URL,
    SERPER_API_KEY,
    SERPLY_API_KEY,
    SERPSTACK_API_KEY,
    SERPSTACK_HTTPS,
    TAVILY_API_KEY,
    TIKA_SERVER_URL,
    UPLOAD_DIR,
    YOUTUBE_LOADER_LANGUAGE,
    DEFAULT_CHROMA_SERVER_HOST,
    DEFAULT_CHROMA_SERVER_PORT,
    AppConfig,
)


class AppStateConfig:
    def __init__(self):
        self.config = AppConfig()

        # Set configuration variables
        self.config.TOP_K = RAG_TOP_K
        self.config.RELEVANCE_THRESHOLD = RAG_RELEVANCE_THRESHOLD
        self.config.FILE_MAX_SIZE = RAG_FILE_MAX_SIZE
        self.config.FILE_MAX_COUNT = RAG_FILE_MAX_COUNT

        self.config.ENABLE_RAG_HYBRID_SEARCH = ENABLE_RAG_HYBRID_SEARCH
        self.config.ENABLE_RAG_WEB_LOADER_SSL_VERIFICATION = ENABLE_RAG_WEB_LOADER_SSL_VERIFICATION

        self.config.CONTENT_EXTRACTION_ENGINE = CONTENT_EXTRACTION_ENGINE
        self.config.TIKA_SERVER_URL = TIKA_SERVER_URL

        self.config.CHUNK_SIZE = CHUNK_SIZE
        self.config.CHUNK_OVERLAP = CHUNK_OVERLAP
        self.config.DEFAULT_OLLAMA_EMBEDDING_MODEL = DEFAULT_OLLAMA_EMBEDDING_MODEL
        # self.config.RAG_EMBEDDING_FUNCTION = RAG_EMBEDDING_FUNCTION
        self.config.RAG_EMBEDDING_ENGINE = RAG_EMBEDDING_ENGINE
        self.config.RAG_EMBEDDING_MODEL = RAG_EMBEDDING_MODEL
        self.config.RAG_EMBEDDING_OPENAI_BATCH_SIZE = RAG_EMBEDDING_OPENAI_BATCH_SIZE
        self.config.RAG_RERANKING_MODEL = RAG_RERANKING_MODEL
        self.config.RAG_TEMPLATE = RAG_TEMPLATE

        self.config.OPENAI_API_BASE_URL = RAG_OPENAI_API_BASE_URL
        self.config.OPENAI_API_KEY = OPENAI_API_KEY
        self.config.OLLAMA_HOST = OLLAMA_HOST
        self.config.OLLAMA_PORT = OLLAMA_PORT

        self.config.PDF_EXTRACT_IMAGES = PDF_EXTRACT_IMAGES

        self.config.YOUTUBE_LOADER_LANGUAGE = YOUTUBE_LOADER_LANGUAGE
        self.YOUTUBE_LOADER_TRANSLATION = None

        self.config.ENABLE_RAG_WEB_SEARCH = ENABLE_RAG_WEB_SEARCH
        self.config.RAG_WEB_SEARCH_ENGINE = RAG_WEB_SEARCH_ENGINE
        self.config.RAG_WEB_SEARCH_DOMAIN_FILTER_LIST = RAG_WEB_SEARCH_DOMAIN_FILTER_LIST

        self.config.DEFAULT_CHROMA_SERVER_PORT = DEFAULT_CHROMA_SERVER_PORT
        self.config.DEFAULT_CHROMA_SERVER_HOST = DEFAULT_CHROMA_SERVER_HOST

        self.config.SEARXNG_QUERY_URL = SEARXNG_QUERY_URL
        self.config.GOOGLE_PSE_API_KEY = GOOGLE_PSE_API_KEY
        self.config.GOOGLE_PSE_ENGINE_ID = GOOGLE_PSE_ENGINE_ID
        self.config.BRAVE_SEARCH_API_KEY = BRAVE_SEARCH_API_KEY
        self.config.SERPSTACK_API_KEY = SERPSTACK_API_KEY
        self.config.SERPSTACK_HTTPS = SERPSTACK_HTTPS
        self.config.SERPER_API_KEY = SERPER_API_KEY
        self.config.SERPLY_API_KEY = SERPLY_API_KEY
        self.config.TAVILY_API_KEY = TAVILY_API_KEY
        self.config.SEARCHAPI_API_KEY = SEARCHAPI_API_KEY
        self.config.SEARCHAPI_ENGINE = SEARCHAPI_ENGINE
        self.config.RAG_WEB_SEARCH_RESULT_COUNT = RAG_WEB_SEARCH_RESULT_COUNT
        self.config.RAG_WEB_SEARCH_CONCURRENT_REQUESTS = RAG_WEB_SEARCH_CONCURRENT_REQUESTS


state = AppStateConfig()