from rai.config import (
    CHUNK_OVERLAP,
    CHUNK_SIZE,
    CONTENT_EXTRACTION_ENGINE,
    DOCS_DIR,
    ENABLE_RAG_HYBRID_SEARCH,
    ENABLE_RAG_WEB_LOADER_SSL_VERIFICATION,
    ENABLE_RAG_WEB_SEARCH,
    PDF_EXTRACT_IMAGES,
    RAG_EMBEDDING_ENGINE,
    RAG_EMBEDDING_MODEL,
    OLLAMA_PORT,
    OLLAMA_HOST,
DEFAULT_OLLAMA_MODEL,
    OPENAI_API_KEY,
DEFAULT_OLLAMA_EMBEDDING_MODEL,
    RAG_EMBEDDING_OPENAI_BATCH_SIZE,
    RAG_FILE_MAX_COUNT,
    RAG_FILE_MAX_SIZE,
    RAG_OPENAI_API_BASE_URL,
    RAG_RELEVANCE_THRESHOLD,
    RAG_RERANKING_MODEL,
    RAG_TOP_K,
    RAG_WEB_SEARCH_DOMAIN_FILTER_LIST,
    RAG_WEB_SEARCH_ENGINE,
    TIKA_SERVER_URL,
    UPLOAD_DIR,
    YOUTUBE_LOADER_LANGUAGE,
    DEFAULT_CHROMA_SERVER_HOST,
    DEFAULT_CHROMA_SERVER_PORT,
    AppConfig,
)


class AppStateConfig:
    def __init__(self):
        self.config = AppConfig()

        # Set configuration variables
        self.config.TOP_K = RAG_TOP_K
        self.config.RELEVANCE_THRESHOLD = RAG_RELEVANCE_THRESHOLD
        self.config.FILE_MAX_SIZE = RAG_FILE_MAX_SIZE
        self.config.FILE_MAX_COUNT = RAG_FILE_MAX_COUNT

        self.config.ENABLE_RAG_HYBRID_SEARCH = ENABLE_RAG_HYBRID_SEARCH
        self.config.ENABLE_RAG_WEB_LOADER_SSL_VERIFICATION = ENABLE_RAG_WEB_LOADER_SSL_VERIFICATION

        self.config.CONTENT_EXTRACTION_ENGINE = CONTENT_EXTRACTION_ENGINE
        self.config.TIKA_SERVER_URL = TIKA_SERVER_URL

        self.config.CHUNK_SIZE = CHUNK_SIZE
        self.config.CHUNK_OVERLAP = CHUNK_OVERLAP
        self.config.DEFAULT_OLLAMA_EMBEDDING_MODEL = DEFAULT_OLLAMA_EMBEDDING_MODEL
        self.config.RAG_EMBEDDING_ENGINE = RAG_EMBEDDING_ENGINE
        self.config.RAG_EMBEDDING_MODEL = RAG_EMBEDDING_MODEL
        self.config.RAG_EMBEDDING_OPENAI_BATCH_SIZE = RAG_EMBEDDING_OPENAI_BATCH_SIZE
        self.config.RAG_RERANKING_MODEL = RAG_RERANKING_MODEL

        self.config.OPENAI_API_BASE_URL = RAG_OPENAI_API_BASE_URL
        self.config.OPENAI_API_KEY = OPENAI_API_KEY
        self.config.OLLAMA_HOST = OLLAMA_HOST
        self.config.OLLAMA_PORT = OLLAMA_PORT
        self.config.DEFAULT_OLLAMA_MODEL = DEFAULT_OLLAMA_MODEL

        self.config.PDF_EXTRACT_IMAGES = PDF_EXTRACT_IMAGES

        self.config.YOUTUBE_LOADER_LANGUAGE = YOUTUBE_LOADER_LANGUAGE
        self.YOUTUBE_LOADER_TRANSLATION = None

        self.config.ENABLE_RAG_WEB_SEARCH = ENABLE_RAG_WEB_SEARCH
        self.config.RAG_WEB_SEARCH_ENGINE = RAG_WEB_SEARCH_ENGINE
        self.config.RAG_WEB_SEARCH_DOMAIN_FILTER_LIST = RAG_WEB_SEARCH_DOMAIN_FILTER_LIST

        self.config.DEFAULT_CHROMA_SERVER_PORT = DEFAULT_CHROMA_SERVER_PORT
        self.config.DEFAULT_CHROMA_SERVER_HOST = DEFAULT_CHROMA_SERVER_HOST



state = AppStateConfig()