# from Utils import FILE
"""
-> Rules
1. Each "topic" has 3 attributes, a. search_terms b. weighted_terms c. rss_feeds
2. Each "topics" attribute starts with the topic name, underscores only.
"""
extended_stop_words = ["with", "more", "s", "has", "have", "they", "this", "their", "was", "not", "said", "also",
                       "most", "but", "from", "whether", "so", "ways", "if", "were", "have", "my", "being", "re", "what",
                       "where", "many", "other", "t", "i", "than", "had", "who", "amoung", "get", "say", "could", "way"]
# meta_names = FILE.load_dict_from_file("meta_names")
# -------------------------------------> CATEGORIES AND THEIR KEY-TERMS <-------------------------------------------- #

MAX_WEIGHT = 200
HIGH_WEIGHT = 130
MIDDLE_WEIGHT = 75
LOW_WEIGHT = 25
MINI_WEIGHT = 10
NANO_WEIGHT = 3

class MainCategories:
    # -> If any lists are added, add here.
    keys = ["search_terms", "weighted_terms", "rss_feeds", "secondary_weighted_terms", "url_sources"]

    def get_var(self, var_name):
        """  GETTER HELPER  """
        return self.__getattribute__(var_name)

    @staticmethod
    def combine_var_name(topic, term):
        return topic + "_" + term

    ####################################################################################################################
    # -> 0. General <-
    ####################################################################################################################
    general = "General"
    general_search_terms = ["business", "government", "federal government", "white house", "politics", "global news",
                            "news", "united states economy", "global economy", "president"]
    
    general_weighted_terms = {
        "program": HIGH_WEIGHT,
        "programs": HIGH_WEIGHT,
        "team snacks": HIGH_WEIGHT,
        "snack rotation": HIGH_WEIGHT,
        "bring snacks": MIDDLE_WEIGHT,
        "packing snacks": MIDDLE_WEIGHT,
        "food": MIDDLE_WEIGHT,
        "extra snacks": MIDDLE_WEIGHT,
        "game day snacks": MIDDLE_WEIGHT,
        "water": LOW_WEIGHT,
        "hydration": LOW_WEIGHT,
        "healthy snacks": MIDDLE_WEIGHT,
        "thousand": LOW_WEIGHT,
          "million": LOW_WEIGHT,
          "billion": MIDDLE_WEIGHT,
          "trillion": MIDDLE_WEIGHT,
          "space": MINI_WEIGHT,
          "mainstream": MINI_WEIGHT,
          "property": NANO_WEIGHT,
          "network": MINI_WEIGHT,
          "future": LOW_WEIGHT,
          "futures": LOW_WEIGHT,
          "crowdfunding": NANO_WEIGHT,
          "economy": MINI_WEIGHT,
          "market valuation": MINI_WEIGHT,
          "Metrics": NANO_WEIGHT,
          "market action": NANO_WEIGHT,
          "dominance": NANO_WEIGHT,
          "assets": MINI_WEIGHT,
          "Drops": NANO_WEIGHT,
          "Dips": NANO_WEIGHT,
          "value proposition": MINI_WEIGHT,
          "fluctuates": NANO_WEIGHT,
          "portfolio": NANO_WEIGHT,
          "crash": NANO_WEIGHT,
          "optimistic": NANO_WEIGHT,
          "projections": NANO_WEIGHT,
          "hedge fund": NANO_WEIGHT,
          "hedgefund": NANO_WEIGHT,
          "holders": NANO_WEIGHT,
          "holder": NANO_WEIGHT,
          "owns": NANO_WEIGHT,
          "fund": NANO_WEIGHT,
          "game": NANO_WEIGHT,
          "gaming": NANO_WEIGHT,
          "market capitalization": LOW_WEIGHT,
          "developer": NANO_WEIGHT,
          "development": NANO_WEIGHT,
          "develop": NANO_WEIGHT,
          "engineer": NANO_WEIGHT,
          "engineering": NANO_WEIGHT,
          "4g": MINI_WEIGHT,
          "5g": MINI_WEIGHT,
          "6g": MINI_WEIGHT,
          "fiber": MINI_WEIGHT,
          "optical": MINI_WEIGHT,
          "fiber optic": MINI_WEIGHT,
          "business": NANO_WEIGHT,
          "businesses": NANO_WEIGHT,
          "meeting": NANO_WEIGHT,
          "meetings": NANO_WEIGHT,
          "committee": NANO_WEIGHT,
          "fed": MINI_WEIGHT,
          "the fed": MINI_WEIGHT,
          "federal": NANO_WEIGHT,
          "federal reserve": LOW_WEIGHT,
          "bull market": NANO_WEIGHT,
          "bear market": NANO_WEIGHT,
          "inflation": MINI_WEIGHT,
          "deflation": MINI_WEIGHT,
          "plunges": MINI_WEIGHT,
          "leaked": MIDDLE_WEIGHT,
          "announcement": MINI_WEIGHT,
        "parent involvement": HIGH_WEIGHT,
        "volunteering": MIDDLE_WEIGHT,
        "help at practice": MIDDLE_WEIGHT,
        "cheering": MIDDLE_WEIGHT,
        "sideline support": MIDDLE_WEIGHT,
        "parent support": MIDDLE_WEIGHT,
        "team involvement": MIDDLE_WEIGHT,
        "discouraged": HIGH_WEIGHT,
        "emotional support": HIGH_WEIGHT,
        "fun": MIDDLE_WEIGHT,
        "motivation": MIDDLE_WEIGHT,
        "confidence building": MIDDLE_WEIGHT,
        "encouragement": MIDDLE_WEIGHT,
        "positive feedback": MIDDLE_WEIGHT,
        "enjoyment": MIDDLE_WEIGHT,
        "handling frustration": MIDDLE_WEIGHT,
        "supporting the child": MIDDLE_WEIGHT,
        "pressure": LOW_WEIGHT,
        "struggling": LOW_WEIGHT,
        "home practice": HIGH_WEIGHT,
        "practice at home": HIGH_WEIGHT,
        "help at home": HIGH_WEIGHT,
        "drills at home": HIGH_WEIGHT,
        "improve skills": HIGH_WEIGHT,
        "improvement at home": MIDDLE_WEIGHT,
        "non-pushy guidance": MIDDLE_WEIGHT,
        "extra practice": MIDDLE_WEIGHT,
        "how can I help": MIDDLE_WEIGHT,
        "improve": MAX_WEIGHT,
        "improvement": MAX_WEIGHT,
        "feels": HIGH_WEIGHT,
        "discouraged": HIGH_WEIGHT,
        "playing time": MAX_WEIGHT,
        "development": MAX_WEIGHT,
        "coaching": MAX_WEIGHT,
        "player development": HIGH_WEIGHT,
        "parent development": MIDDLE_WEIGHT,
        "training": HIGH_WEIGHT,
        "skills": HIGH_WEIGHT,
        "skill-building": MIDDLE_WEIGHT,
        "growth": HIGH_WEIGHT,
        "improvement": HIGH_WEIGHT,
        "plan": HIGH_WEIGHT,
        "strategy": HIGH_WEIGHT,
        "theory": MIDDLE_WEIGHT,
        "guidance": HIGH_WEIGHT,
        "instruction": MIDDLE_WEIGHT,
        "mentor": MIDDLE_WEIGHT,
        "mentorship": MIDDLE_WEIGHT,
        "tips": MIDDLE_WEIGHT,
        "advice": HIGH_WEIGHT,
        "session": MIDDLE_WEIGHT,
        "session plan": MIDDLE_WEIGHT,
        "practice drill": HIGH_WEIGHT,
        "warm-up": MIDDLE_WEIGHT,
        "cool down": MIDDLE_WEIGHT,
        "exercise": MIDDLE_WEIGHT,
        "drills": HIGH_WEIGHT,
        "progress": HIGH_WEIGHT,
        "technique": HIGH_WEIGHT,
        "practice plan": HIGH_WEIGHT,
        "coaching plan": HIGH_WEIGHT,
        "feedback": MIDDLE_WEIGHT,
        "evaluation": MIDDLE_WEIGHT,
        "performance": MIDDLE_WEIGHT,
        "assessment": MIDDLE_WEIGHT,
        "sportsmanship": MINI_WEIGHT,
        "competition": MINI_WEIGHT,
        "motivational": MINI_WEIGHT,
        "goal setting": MIDDLE_WEIGHT,
        "leadership": MIDDLE_WEIGHT,
        "communication": MIDDLE_WEIGHT,
        "team building": MIDDLE_WEIGHT,
        "confidence": MINI_WEIGHT,
        "positivity": MINI_WEIGHT,
        "mindset": LOW_WEIGHT,
        "resilience": LOW_WEIGHT,
        "game theory": LOW_WEIGHT,
        "positioning": MINI_WEIGHT,
        "conditioning": LOW_WEIGHT,
        "endurance": LOW_WEIGHT,
        "strength training": LOW_WEIGHT,
        "agility": LOW_WEIGHT,
        "speed training": LOW_WEIGHT,
        "nutrition": LOW_WEIGHT,
        "hydration": LOW_WEIGHT,
        "game plan": MIDDLE_WEIGHT,
        "tactics": MIDDLE_WEIGHT,
        "strategy session": LOW_WEIGHT,
        "position": MINI_WEIGHT,
        "role": MINI_WEIGHT,
        "field awareness": MINI_WEIGHT,
        "decision making": LOW_WEIGHT,
        "mental skills": LOW_WEIGHT,
        "concentration": MINI_WEIGHT,
        "focus": MINI_WEIGHT,
        "discipline": LOW_WEIGHT,
        "recovery": MINI_WEIGHT,
        "injury prevention": LOW_WEIGHT,
        "fitness": MINI_WEIGHT,
        "stretching": MINI_WEIGHT,
        "how to improve": MIDDLE_WEIGHT,
        "how should I do": MIDDLE_WEIGHT,
        "how can I be a better": MIDDLE_WEIGHT,
        "what should I do as a": MIDDLE_WEIGHT,
        "best practices": LOW_WEIGHT,
        "tips for success": LOW_WEIGHT,
        "parent involvement": LOW_WEIGHT,
        "coach feedback": MINI_WEIGHT,
        "coach evaluation": MINI_WEIGHT,
        "training schedule": MINI_WEIGHT,
        "weekly goals": MINI_WEIGHT,
        "monthly goals": MINI_WEIGHT,
        "skills assessment": MINI_WEIGHT,
        "game review": MINI_WEIGHT,
        "tactical awareness": MINI_WEIGHT,
        "playing time": HIGH_WEIGHT,
        "game time": HIGH_WEIGHT,
        "participation": HIGH_WEIGHT,
        "inclusion": HIGH_WEIGHT,
        "equal play": MIDDLE_WEIGHT,
        "rotation": MIDDLE_WEIGHT,
        "learning time": MIDDLE_WEIGHT,
        "bench": LOW_WEIGHT,
        "on the field": MIDDLE_WEIGHT,
        "feeling included": MIDDLE_WEIGHT
    }
    ####################################################################################################################
    # -> 1. Finance <-
    ####################################################################################################################
    finance = "Finance"
    finance_search_terms = ["money", "finance", "payment", "budget", "investment", "loan", "interest rate",
                            "financial planning", "stock market", "savings", "banking", "credit", "debt", "taxes"]

    finance_weighted_terms = {
        "cost": MAX_WEIGHT,
        "money": MAX_WEIGHT,
        "payment": HIGH_WEIGHT,
        "finance": HIGH_WEIGHT,
        "budget": MIDDLE_WEIGHT,
        "investment": HIGH_WEIGHT,
        "loan": MIDDLE_WEIGHT,
        "interest": MIDDLE_WEIGHT,
        "interest rate": HIGH_WEIGHT,
        "financial planning": HIGH_WEIGHT,
        "stock market": HIGH_WEIGHT,
        "savings": MIDDLE_WEIGHT,
        "bank": LOW_WEIGHT,
        "banking": LOW_WEIGHT,
        "credit": HIGH_WEIGHT,
        "debt": MIDDLE_WEIGHT,
        "tax": HIGH_WEIGHT,
        "taxes": HIGH_WEIGHT,
        "return on investment": HIGH_WEIGHT,
        "ROI": MIDDLE_WEIGHT,
        "dividend": MIDDLE_WEIGHT,
        "expense": LOW_WEIGHT,
        "capital": LOW_WEIGHT,
        "equity": MIDDLE_WEIGHT,
        "portfolio": LOW_WEIGHT,
        "asset": LOW_WEIGHT,
        "liability": LOW_WEIGHT,
        "balance sheet": MIDDLE_WEIGHT,
        "revenue": HIGH_WEIGHT,
        "profit": HIGH_WEIGHT,
        "loss": HIGH_WEIGHT,
        "income": MIDDLE_WEIGHT,
        "cash flow": HIGH_WEIGHT,
        "net worth": MIDDLE_WEIGHT,
        "valuation": MIDDLE_WEIGHT,
        "valuation metrics": MIDDLE_WEIGHT,
        "stocks": MIDDLE_WEIGHT,
        "shares": MIDDLE_WEIGHT,
        "bonds": MIDDLE_WEIGHT,
        "mutual funds": MIDDLE_WEIGHT,
        "ETF": MIDDLE_WEIGHT,
        "forex": MINI_WEIGHT,
        "currency": LOW_WEIGHT,
        "exchange": MINI_WEIGHT,
        "financial advisor": MINI_WEIGHT,
        "broker": MINI_WEIGHT,
        "pension": MIDDLE_WEIGHT,
        "insurance": MINI_WEIGHT,
        "real estate": LOW_WEIGHT,
        "mortgage": MIDDLE_WEIGHT,
        "credit score": MIDDLE_WEIGHT,
        "savings account": MINI_WEIGHT,
        "checking account": MINI_WEIGHT,
        "fiscal policy": MINI_WEIGHT,
        "monetary policy": MINI_WEIGHT,
        "inflation": LOW_WEIGHT,
        "deflation": LOW_WEIGHT,
        "economic recession": LOW_WEIGHT,
        "GDP": LOW_WEIGHT,
        "currency exchange": MINI_WEIGHT,
        "financial crisis": MINI_WEIGHT,
        "bankruptcy": MINI_WEIGHT,
        "audit": MINI_WEIGHT,
        "accounting": NANO_WEIGHT,
        "account": NANO_WEIGHT,
        "ledger": NANO_WEIGHT,
        "capital gain": MINI_WEIGHT,
        "depreciation": MINI_WEIGHT,
        "amortization": MINI_WEIGHT,
        "write-off": MINI_WEIGHT,
        "tax return": MINI_WEIGHT,
        "deduction": MINI_WEIGHT,
        "capital asset": MINI_WEIGHT,
        "principal": MINI_WEIGHT,
        "yield": MINI_WEIGHT,
        "diversification": MINI_WEIGHT,
        "hedging": MINI_WEIGHT,
        "buyback": MINI_WEIGHT,
        "option": MINI_WEIGHT,
        "futures": MINI_WEIGHT,
        "commodities": MINI_WEIGHT,
        "derivatives": MINI_WEIGHT,
        "financial statement": MINI_WEIGHT,
        "balance": MINI_WEIGHT,
        "revenue stream": MINI_WEIGHT,
        "cash reserve": MINI_WEIGHT,
        "credit risk": MINI_WEIGHT,
        "expenditure": NANO_WEIGHT,
        "liquid assets": NANO_WEIGHT,
        "fixed assets": NANO_WEIGHT,
        "debit": NANO_WEIGHT,
        "credit line": NANO_WEIGHT,
        "overdraft": NANO_WEIGHT,
        "bond yield": NANO_WEIGHT,
        "bull market": MINI_WEIGHT,
        "bear market": MINI_WEIGHT,
        "market volatility": MINI_WEIGHT,

    }
    ####################################################################################################################
    # -> 2. Schedule <-
    ####################################################################################################################
    schedule = "Schedule"
    schedule_search_terms = ["schedule", "time", "location", "place", "where", "when", "event", "appointment",
                             "registration",
                             "field", "complex", "game time", "practice time", "meeting time", "availability", "book",
                             "booking", "reserve", "calendar"]

    schedule_weighted_terms = {
        "often": MIDDLE_WEIGHT,
        "how often": HIGH_WEIGHT,
        "practices": HIGH_WEIGHT,
        "trainings": MIDDLE_WEIGHT,
        "practice": HIGH_WEIGHT,
        "long": MIDDLE_WEIGHT,
        "how long": HIGH_WEIGHT,
        "schedule": MAX_WEIGHT,
        "time": HIGH_WEIGHT,
        "location": HIGH_WEIGHT,
        "place": MIDDLE_WEIGHT,
        "where": MIDDLE_WEIGHT,
        "when": MIDDLE_WEIGHT,
        "event": HIGH_WEIGHT,
        "appointment": MIDDLE_WEIGHT,
        "registration": HIGH_WEIGHT,
        "field": HIGH_WEIGHT,
        "complex": HIGH_WEIGHT,
        "game time": HIGH_WEIGHT,
        "practice time": HIGH_WEIGHT,
        "meeting time": MIDDLE_WEIGHT,
        "availability": HIGH_WEIGHT,
        "calendar": MIDDLE_WEIGHT,
        "reservation": MIDDLE_WEIGHT,
        "booking": MIDDLE_WEIGHT,
        "book": MIDDLE_WEIGHT,
        "reserve": MIDDLE_WEIGHT,
        "session": MIDDLE_WEIGHT,
        "session time": MIDDLE_WEIGHT,
        "conference": MIDDLE_WEIGHT,
        "event time": HIGH_WEIGHT,
        "event date": MIDDLE_WEIGHT,
        "date": MIDDLE_WEIGHT,
        "day": LOW_WEIGHT,
        "week": LOW_WEIGHT,
        "month": LOW_WEIGHT,
        "year": LOW_WEIGHT,
        "morning": LOW_WEIGHT,
        "afternoon": LOW_WEIGHT,
        "evening": LOW_WEIGHT,
        "night": LOW_WEIGHT,
        "quarter": NANO_WEIGHT,
        "half hour": LOW_WEIGHT,
        "quarter hour": NANO_WEIGHT,
        "schedule update": LOW_WEIGHT,
        "calendar invite": MIDDLE_WEIGHT,
        "reminder": MIDDLE_WEIGHT,
        "time slot": LOW_WEIGHT,
        "timing": MINI_WEIGHT,
        "check-in": MINI_WEIGHT,
        "check-out": MINI_WEIGHT,
        "itinerary": MINI_WEIGHT,
        "agenda": MINI_WEIGHT,
        "hours": MINI_WEIGHT,
        "days": MINI_WEIGHT,
        "weeks": MINI_WEIGHT,
        "months": MINI_WEIGHT,
        "facility": MINI_WEIGHT,
        "venue": MINI_WEIGHT,
        "timezone": MINI_WEIGHT,
        "coordinate": MINI_WEIGHT,
        "arrival": MINI_WEIGHT,
        "departure": MINI_WEIGHT,
        "appointment time": LOW_WEIGHT,
        "deadline": MINI_WEIGHT,
        "due date": MINI_WEIGHT,
        "cutoff": MINI_WEIGHT,
        "opening hours": MINI_WEIGHT,
        "working hours": MINI_WEIGHT,
        "office hours": MINI_WEIGHT,
        "session start": MINI_WEIGHT,
        "session end": MINI_WEIGHT,
        "meeting location": MINI_WEIGHT,
        "map": MINI_WEIGHT,
        "directions": MINI_WEIGHT,
        "route": MINI_WEIGHT,
        "nearby": MINI_WEIGHT,
        "proximity": MINI_WEIGHT,
        "attendance": MINI_WEIGHT,
        "visit": MINI_WEIGHT,
        "arrival time": MINI_WEIGHT,
        "departure time": MINI_WEIGHT,
        "duration": MINI_WEIGHT,
        "timespan": NANO_WEIGHT,
        "date range": NANO_WEIGHT,
        "season": NANO_WEIGHT,
        "game schedule": HIGH_WEIGHT,
        "game locations": HIGH_WEIGHT,
        "field location": HIGH_WEIGHT,
        "travel": MIDDLE_WEIGHT,
        "home field": MIDDLE_WEIGHT,
        "away game": MIDDLE_WEIGHT,
        "different fields": MIDDLE_WEIGHT,
        "venue change": LOW_WEIGHT,
        "weather cancellation": HIGH_WEIGHT,
        "bad weather": HIGH_WEIGHT,
        "rain": HIGH_WEIGHT,
        "hot weather": HIGH_WEIGHT,
        "extreme heat": HIGH_WEIGHT,
        "cancel practice": HIGH_WEIGHT,
        "cancel games": HIGH_WEIGHT,
        "prepare for weather": MIDDLE_WEIGHT,
        "reschedule": MIDDLE_WEIGHT,
        "weather conditions": MIDDLE_WEIGHT,
        "weather policy": MIDDLE_WEIGHT,
        "postponed": MIDDLE_WEIGHT,
        "duration": HIGH_WEIGHT,
        "frequency": HIGH_WEIGHT,
        "last": MIDDLE_WEIGHT,
        "exhausted": MIDDLE_WEIGHT,
        "too tired": MIDDLE_WEIGHT,
        "game schedule": HIGH_WEIGHT,
        "travel": MIDDLE_WEIGHT,
        "field": MIDDLE_WEIGHT,
        "different fields": MIDDLE_WEIGHT,
        "cancel": HIGH_WEIGHT,
        "cancellation": HIGH_WEIGHT,
        "rain": MIDDLE_WEIGHT,
        "hot": MIDDLE_WEIGHT,
        "practice frequency": HIGH_WEIGHT,
        "practice duration": HIGH_WEIGHT,
    }
    ####################################################################################################################
    # -> 3. Development <-
    ####################################################################################################################
    # development = "general"
    # development_search_terms = ["sports development", "coaching", "player development", "parent involvement",
    #                             "skills", "training", "growth", "improvement", "development plan", "strategy",
    #                             "coaching theory", "guidance", "instruction", "how to", "tips", "advice",
    #                             "mentor", "coaching session", "coaching plan"]
    #
    # development_weighted_terms = {
    #     "parent involvement": HIGH_WEIGHT,
    #     "volunteering": MIDDLE_WEIGHT,
    #     "help at practice": MIDDLE_WEIGHT,
    #     "cheering": MIDDLE_WEIGHT,
    #     "sideline support": MIDDLE_WEIGHT,
    #     "parent support": MIDDLE_WEIGHT,
    #     "team involvement": MIDDLE_WEIGHT,
    #     "discouraged": HIGH_WEIGHT,
    #     "emotional support": HIGH_WEIGHT,
    #     "fun": MIDDLE_WEIGHT,
    #     "motivation": MIDDLE_WEIGHT,
    #     "confidence building": MIDDLE_WEIGHT,
    #     "encouragement": MIDDLE_WEIGHT,
    #     "positive feedback": MIDDLE_WEIGHT,
    #     "enjoyment": MIDDLE_WEIGHT,
    #     "handling frustration": MIDDLE_WEIGHT,
    #     "supporting the child": MIDDLE_WEIGHT,
    #     "pressure": LOW_WEIGHT,
    #     "struggling": LOW_WEIGHT,
    #     "home practice": HIGH_WEIGHT,
    #     "practice at home": HIGH_WEIGHT,
    #     "help at home": HIGH_WEIGHT,
    #     "drills at home": HIGH_WEIGHT,
    #     "improve skills": HIGH_WEIGHT,
    #     "improvement at home": MIDDLE_WEIGHT,
    #     "non-pushy guidance": MIDDLE_WEIGHT,
    #     "extra practice": MIDDLE_WEIGHT,
    #     "how can I help": MIDDLE_WEIGHT,
    #     "improve": MAX_WEIGHT,
    #     "improvement": MAX_WEIGHT,
    #     "feels": HIGH_WEIGHT,
    #     "discouraged": HIGH_WEIGHT,
    #     "playing time": MAX_WEIGHT,
    #     "development": MAX_WEIGHT,
    #     "coaching": MAX_WEIGHT,
    #     "player development": HIGH_WEIGHT,
    #     "parent development": MIDDLE_WEIGHT,
    #     "training": HIGH_WEIGHT,
    #     "skills": HIGH_WEIGHT,
    #     "skill-building": MIDDLE_WEIGHT,
    #     "growth": HIGH_WEIGHT,
    #     "improvement": HIGH_WEIGHT,
    #     "plan": HIGH_WEIGHT,
    #     "strategy": HIGH_WEIGHT,
    #     "theory": MIDDLE_WEIGHT,
    #     "guidance": HIGH_WEIGHT,
    #     "instruction": MIDDLE_WEIGHT,
    #     "mentor": MIDDLE_WEIGHT,
    #     "mentorship": MIDDLE_WEIGHT,
    #     "tips": MIDDLE_WEIGHT,
    #     "advice": HIGH_WEIGHT,
    #     "session": MIDDLE_WEIGHT,
    #     "session plan": MIDDLE_WEIGHT,
    #     "practice drill": HIGH_WEIGHT,
    #     "warm-up": MIDDLE_WEIGHT,
    #     "cool down": MIDDLE_WEIGHT,
    #     "exercise": MIDDLE_WEIGHT,
    #     "drills": HIGH_WEIGHT,
    #     "progress": HIGH_WEIGHT,
    #     "technique": HIGH_WEIGHT,
    #     "practice plan": HIGH_WEIGHT,
    #     "coaching plan": HIGH_WEIGHT,
    #     "feedback": MIDDLE_WEIGHT,
    #     "evaluation": MIDDLE_WEIGHT,
    #     "performance": MIDDLE_WEIGHT,
    #     "assessment": MIDDLE_WEIGHT,
    #     "sportsmanship": MINI_WEIGHT,
    #     "competition": MINI_WEIGHT,
    #     "motivational": MINI_WEIGHT,
    #     "goal setting": MIDDLE_WEIGHT,
    #     "leadership": MIDDLE_WEIGHT,
    #     "communication": MIDDLE_WEIGHT,
    #     "team building": MIDDLE_WEIGHT,
    #     "confidence": MINI_WEIGHT,
    #     "positivity": MINI_WEIGHT,
    #     "mindset": LOW_WEIGHT,
    #     "resilience": LOW_WEIGHT,
    #     "game theory": LOW_WEIGHT,
    #     "positioning": MINI_WEIGHT,
    #     "conditioning": LOW_WEIGHT,
    #     "endurance": LOW_WEIGHT,
    #     "strength training": LOW_WEIGHT,
    #     "agility": LOW_WEIGHT,
    #     "speed training": LOW_WEIGHT,
    #     "nutrition": LOW_WEIGHT,
    #     "hydration": LOW_WEIGHT,
    #     "game plan": MIDDLE_WEIGHT,
    #     "tactics": MIDDLE_WEIGHT,
    #     "strategy session": LOW_WEIGHT,
    #     "position": MINI_WEIGHT,
    #     "role": MINI_WEIGHT,
    #     "field awareness": MINI_WEIGHT,
    #     "decision making": LOW_WEIGHT,
    #     "mental skills": LOW_WEIGHT,
    #     "concentration": MINI_WEIGHT,
    #     "focus": MINI_WEIGHT,
    #     "discipline": LOW_WEIGHT,
    #     "recovery": MINI_WEIGHT,
    #     "injury prevention": LOW_WEIGHT,
    #     "fitness": MINI_WEIGHT,
    #     "stretching": MINI_WEIGHT,
    #     "how to improve": MIDDLE_WEIGHT,
    #     "how should I do": MIDDLE_WEIGHT,
    #     "how can I be a better": MIDDLE_WEIGHT,
    #     "what should I do as a": MIDDLE_WEIGHT,
    #     "best practices": LOW_WEIGHT,
    #     "tips for success": LOW_WEIGHT,
    #     "parent involvement": LOW_WEIGHT,
    #     "coach feedback": MINI_WEIGHT,
    #     "coach evaluation": MINI_WEIGHT,
    #     "training schedule": MINI_WEIGHT,
    #     "weekly goals": MINI_WEIGHT,
    #     "monthly goals": MINI_WEIGHT,
    #     "skills assessment": MINI_WEIGHT,
    #     "game review": MINI_WEIGHT,
    #     "tactical awareness": MINI_WEIGHT,
    #     "playing time": HIGH_WEIGHT,
    #     "game time": HIGH_WEIGHT,
    #     "participation": HIGH_WEIGHT,
    #     "inclusion": HIGH_WEIGHT,
    #     "equal play": MIDDLE_WEIGHT,
    #     "rotation": MIDDLE_WEIGHT,
    #     "learning time": MIDDLE_WEIGHT,
    #     "bench": LOW_WEIGHT,
    #     "on the field": MIDDLE_WEIGHT,
    #     "feeling included": MIDDLE_WEIGHT,
    # }
    safety = "Safety"
    safety_search_terms = ["medical staff", "first aid", "injury prevention", "safety", "emergency", "first aid kit",
                           "injuries"]

    safety_weighted_terms = {
        "medical staff": HIGH_WEIGHT,
        "first aid kit": HIGH_WEIGHT,
        "injury": HIGH_WEIGHT,
        "safety protocols": HIGH_WEIGHT,
        "first responder": MIDDLE_WEIGHT,
        "emergency procedures": HIGH_WEIGHT,
        "small scrape": LOW_WEIGHT,
        "injury prevention": MIDDLE_WEIGHT,
        "sports injury": MIDDLE_WEIGHT,
        "accident": LOW_WEIGHT,
        "treatment": LOW_WEIGHT,
    }

    ####################################################################################################################
    # -> 2.  <-
    ####################################################################################################################


    ####################################################################################################################
    # -> 3.  <-
    ####################################################################################################################




    @staticmethod
    def get_main_fopic_category_names():
        test = MainCategories.__dict__.keys()
        variables = []
        for item in test:
            if str(item).startswith("__"):
                continue
            elif str(item).startswith("keys"):
                continue
            elif str(item).__contains__("_"):
                continue
            else:
                variables.append(item)
        return variables